#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing dependencies..." --weight=20

ynh_exec_warn_less ynh_install_nodejs --nodejs_version=$nodejs_version

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

ynh_setup_source --dest_dir="$install_dir"

# Supprimer les fichiers dupliqués
bash "$install_dir/remove_duplicates.sh"
rm -f "$install_dir/remove_duplicates.sh"

chown -R $app:www-data "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations..." --weight=1

ynh_add_nginx_config

# Create log directory
mkdir -p "/var/log/$app"
chown $app:$app "/var/log/$app"

# Create log directory
mkdir -p "/var/log/$app"
chown $app:$app "/var/log/$app"

ynh_add_systemd_config

yunohost service add $app --description="Liberchat encrypted chat" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression --message="Installing $app..." --weight=10

pushd "$install_dir"
	ynh_use_nodejs
	# Fix for ARM64 rollup issue
	ynh_exec_warn_less ynh_exec_as $app env $ynh_node_load_PATH rm -rf node_modules package-lock.json
	ynh_exec_warn_less ynh_exec_as $app env $ynh_node_load_PATH npm install --production
	ynh_exec_warn_less ynh_exec_as $app env $ynh_node_load_PATH npm install express
	ynh_exec_warn_less ynh_exec_as $app env $ynh_node_load_PATH npm run build -- --base=/liberchat/
popd

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

ynh_add_config --template="../conf/.env" --destination="$install_dir/.env"

chmod 400 "$install_dir/.env"
chown $app:$app "$install_dir/.env"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
